apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsproj
  template:
    metadata:
      labels:
        app: devopsproj
    spec:
      containers:
        - name: devopsproj
          image: shuklapratyusha/devops_repo:latest
          ports:
            - containerPort: 80
