apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 3 # Number of replicas for scalability
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: shuklapratyusha/devops_repo:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: react-app-config
