apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops_proj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops_proj
  template:
    metadata:
      labels:
        app: devops_proj
    spec:
      containers:
        - name: devops_proj
          image: shuklapratyusha/devops_repo:latest
          ports:
            - containerPort: 80
